/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectosenus;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import javax.swing.JOptionPane;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellType;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.ss.usermodel.WorkbookFactory;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author drank
 */
public class EjercicioBaloncestoExcel extends javax.swing.JFrame {
    private static String nombreJugador;
    private static Integer tirosDe2, triples, tirosRealizados;
    /**
     * Creates new form EjercicioBaloncestoExcel
     */
    public EjercicioBaloncestoExcel() {
        
        initComponents();
        setLocationRelativeTo(null);
        this.setResizable(false);
        this.setTitle("Estadísticas Baloncesto");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        campoTextoJugador = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        numTirosDe2Metidos = new javax.swing.JSpinner();
        numTriplesMetidos = new javax.swing.JSpinner();
        numTirosRealizados = new javax.swing.JSpinner();
        botonInsertar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        campoTextoJugador.setToolTipText("Inserta el nombre");

        jLabel2.setText("Nombre Jugador:");

        jLabel3.setText("Tiros de 2 metidos:");

        jLabel4.setText("Triples metidos:");

        jLabel5.setText("Tiros realizados:");

        numTirosDe2Metidos.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        numTirosDe2Metidos.setPreferredSize(new java.awt.Dimension(90, 25));

        numTriplesMetidos.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        numTriplesMetidos.setPreferredSize(new java.awt.Dimension(90, 25));

        numTirosRealizados.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        numTirosRealizados.setPreferredSize(new java.awt.Dimension(90, 25));

        botonInsertar.setText("Insertar Datos");
        botonInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInsertarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoTextoJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(168, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numTriplesMetidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numTirosDe2Metidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(botonInsertar)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numTirosRealizados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoTextoJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(numTirosDe2Metidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(numTriplesMetidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(numTirosRealizados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(botonInsertar)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInsertarActionPerformed
        nombreJugador = campoTextoJugador.getText();
        tirosDe2 = (Integer) numTirosDe2Metidos.getValue();
        triples = (Integer) numTriplesMetidos.getValue();
        tirosRealizados = (Integer) numTirosRealizados.getValue();
        
        if (nombreJugador == null || nombreJugador.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Inserte un nombre.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (tirosRealizados == 0) {
            JOptionPane.showMessageDialog(this, "Los tiros realizados debe ser mayor a 0.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        crearInforme(nombreJugador, tirosDe2, triples, tirosRealizados);
        JOptionPane.showMessageDialog(this, "Datos insertados.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_botonInsertarActionPerformed

    private static void crearInforme(String nombreJugador, Integer tirosDe2, Integer triples, Integer tirosRealizados) {
        String nombreArchivo = "jugadores_baloncesto.xlsx";
        String nombreHoja = "Version1";
        boolean archivoExistente = verificarArchivoExistente(nombreArchivo);
        
        
        try (Workbook libroTrabajo = archivoExistente ? WorkbookFactory.create(new FileInputStream(nombreArchivo)) : new XSSFWorkbook()) {
            Sheet hoja = libroTrabajo.getSheet(nombreHoja);
            
            if (hoja == null) {
                hoja = libroTrabajo.createSheet(nombreHoja);
                Row fila = hoja.createRow(0);
                fila.createCell(0).setCellValue("Jugador");
                fila.createCell(1).setCellValue("Tiros de 2 metidos");
                fila.createCell(2).setCellValue("Triples metidos");
                fila.createCell(3).setCellValue("Tiros realizados");
                fila.createCell(4).setCellValue("FG%");
                fila.createCell(5).setCellValue("eFG%");
            }
            Double FG = ((double) (tirosDe2 + triples) / tirosRealizados) * 100;
            Double eFG = (((tirosDe2 + triples) + (0.5 * triples)) / tirosRealizados) * 100;
            
            int filaNumero = hoja.getPhysicalNumberOfRows();
        
            Row fila = hoja.createRow(filaNumero);
            Cell celda = fila.createCell(0, CellType.STRING);
            celda.setCellValue(nombreJugador);
            celda = fila.createCell(1, CellType.NUMERIC);
            celda.setCellValue(tirosDe2);
            celda = fila.createCell(2, CellType.NUMERIC);
            celda.setCellValue(triples);
            celda = fila.createCell(3, CellType.NUMERIC);
            celda.setCellValue(tirosRealizados);
            celda = fila.createCell(4, CellType.NUMERIC);
            celda.setCellValue(FG);
            celda = fila.createCell(5, CellType.NUMERIC);
            celda.setCellValue(eFG);

            try (FileOutputStream archivoSalida = new FileOutputStream(nombreArchivo)) {
                libroTrabajo.write(archivoSalida);
                System.out.println("Datos agregados al archivo Excel correctamente.");
            }
            
        } catch (IOException e) {
                e.printStackTrace();
            }
        
        // Reabrir el archivo y leer los datos actualizados
        try (Workbook libroTrabajo = WorkbookFactory.create(new FileInputStream(nombreArchivo))) {
            Sheet hoja = libroTrabajo.getSheet(nombreHoja);
            int filaNumero = hoja.getPhysicalNumberOfRows();

            System.out.println("Datos actualizados en el archivo:");
            for (int i = 0; i < filaNumero; i++) {
                Row filab = hoja.getRow(i);
                if (filab != null) { // Verifica que la fila no esté vacía
                    for (int cellIndex = 0; cellIndex < filab.getLastCellNum(); cellIndex++) {
                        Cell celda = filab.getCell(cellIndex);

                        // Verifica si la celda contiene algún valor
                        if (celda != null) {
                            System.out.println("Valor encontrado en hoja " + hoja.getSheetName() + ", fila " + (i + 1) + ", columna " + (cellIndex + 1) + ": " + celda.toString());
                        }
                    }
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    
    private static boolean verificarArchivoExistente(String nombreArchivo) {
        return new File(nombreArchivo).exists();
    }
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EjercicioBaloncestoExcel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EjercicioBaloncestoExcel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EjercicioBaloncestoExcel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EjercicioBaloncestoExcel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EjercicioBaloncestoExcel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonInsertar;
    private javax.swing.JTextField campoTextoJugador;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner numTirosDe2Metidos;
    private javax.swing.JSpinner numTirosRealizados;
    private javax.swing.JSpinner numTriplesMetidos;
    // End of variables declaration//GEN-END:variables
}
